"""Aggregated data endpoint for the /resume page.

The downloadable PDF is generated by app/resume_pdf.py and served at
/resume.pdf via the seo router.
"""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.database import get_db
from app import models, schemas

router = APIRouter(prefix="/resume", tags=["resume"])


@router.get("/data")
async def resume_data(db: AsyncSession = Depends(get_db)):
    """Aggregated payload for the /resume page — one request instead of five."""
    about_r = await db.execute(select(models.About).where(models.About.id == 1))
    experience_r = await db.execute(select(models.Experience).order_by(models.Experience.sort_order))
    skills_r = await db.execute(select(models.Skill).order_by(models.Skill.sort_order))
    projects_r = await db.execute(select(models.Project).order_by(models.Project.sort_order))
    coursework_r = await db.execute(select(models.Coursework).order_by(models.Coursework.sort_order))
    return {
        "about": schemas.AboutResponse.model_validate(about_r.scalar_one_or_none()).model_dump(),
        "experience": [schemas.ExperienceResponse.model_validate(e).model_dump() for e in experience_r.scalars().all()],
        "skills": [schemas.SkillResponse.model_validate(s).model_dump() for s in skills_r.scalars().all()],
        "projects": [schemas.ProjectResponse.model_validate(p).model_dump() for p in projects_r.scalars().all()],
        "coursework": [schemas.CourseworkResponse.model_validate(c).model_dump() for c in coursework_r.scalars().all()],
    }
