"""Aggregated data endpoint for the /resume page + résumé variant CRUD.

The downloadable PDF is generated by app/resume_pdf.py and served at
/resume.pdf via the seo router (which honours the ?variant= flavor).
"""

from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.database import get_db
from app import models, schemas
from app.auth import require_auth
from app.utils import sort_experience

router = APIRouter(prefix="/resume", tags=["resume"])


async def _clear_other_defaults(db: AsyncSession, keep_id: int | None) -> None:
    """Only one variant may be the default; unset the flag on all others."""
    rows = await db.execute(select(models.ResumeVariant).where(models.ResumeVariant.is_default == True))  # noqa: E712
    for v in rows.scalars().all():
        if v.id != keep_id:
            v.is_default = False


@router.get("/variants", response_model=List[schemas.ResumeVariantResponse])
async def list_variants(db: AsyncSession = Depends(get_db)):
    result = await db.execute(
        select(models.ResumeVariant).order_by(models.ResumeVariant.sort_order, models.ResumeVariant.id)
    )
    return result.scalars().all()


@router.post("/variants", response_model=schemas.ResumeVariantResponse, status_code=status.HTTP_201_CREATED)
async def create_variant(payload: schemas.ResumeVariantCreate, db: AsyncSession = Depends(get_db), _: None = Depends(require_auth)):
    variant = models.ResumeVariant(**payload.model_dump())
    db.add(variant)
    await db.flush()
    if variant.is_default:
        await _clear_other_defaults(db, variant.id)
    await db.commit()
    await db.refresh(variant)
    return variant


@router.put("/variants/{variant_id}", response_model=schemas.ResumeVariantResponse)
async def update_variant(variant_id: int, payload: schemas.ResumeVariantUpdate, db: AsyncSession = Depends(get_db), _: None = Depends(require_auth)):
    result = await db.execute(select(models.ResumeVariant).where(models.ResumeVariant.id == variant_id))
    variant = result.scalar_one_or_none()
    if not variant:
        raise HTTPException(status_code=404, detail="Variant not found")
    for key, value in payload.model_dump(exclude_unset=True).items():
        setattr(variant, key, value)
    if variant.is_default:
        await _clear_other_defaults(db, variant.id)
    await db.commit()
    await db.refresh(variant)
    return variant


@router.delete("/variants/{variant_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_variant(variant_id: int, db: AsyncSession = Depends(get_db), _: None = Depends(require_auth)):
    result = await db.execute(select(models.ResumeVariant).where(models.ResumeVariant.id == variant_id))
    variant = result.scalar_one_or_none()
    if not variant:
        raise HTTPException(status_code=404, detail="Variant not found")
    await db.delete(variant)
    await db.commit()


@router.get("/data")
async def resume_data(db: AsyncSession = Depends(get_db)):
    """Aggregated payload for the /resume page — one request instead of several."""
    about_r = await db.execute(select(models.About).where(models.About.id == 1))
    experience_r = await db.execute(select(models.Experience).order_by(models.Experience.sort_order))
    skills_r = await db.execute(select(models.Skill).order_by(models.Skill.sort_order))
    projects_r = await db.execute(select(models.Project).order_by(models.Project.sort_order))
    coursework_r = await db.execute(select(models.Coursework).order_by(models.Coursework.sort_order))
    variants_r = await db.execute(
        select(models.ResumeVariant).order_by(models.ResumeVariant.sort_order, models.ResumeVariant.id)
    )
    return {
        "about": schemas.AboutResponse.model_validate(about_r.scalar_one_or_none()).model_dump(),
        "experience": [schemas.ExperienceResponse.model_validate(e).model_dump() for e in sort_experience(experience_r.scalars().all())],
        "skills": [schemas.SkillResponse.model_validate(s).model_dump() for s in skills_r.scalars().all()],
        "projects": [schemas.ProjectResponse.model_validate(p).model_dump() for p in projects_r.scalars().all()],
        "coursework": [schemas.CourseworkResponse.model_validate(c).model_dump() for c in coursework_r.scalars().all()],
        "variants": [schemas.ResumeVariantResponse.model_validate(v).model_dump() for v in variants_r.scalars().all()],
    }
